### ISSUE TITLE
HCIdump' object has no attribute 'isAlive

### ISSUE THREAD

**Issue by giuscond** [custom-components/sensor.mitemp_bt#122]
Hello,
I recently update python to 3.9 and after the custom component stopped to work. I tried to update the component but nothing change.  I checkhed with "sudo getcap `readlink -f \`which python3\``"  and the result was"/usr/local/bin/python3.9 = cap_net_admin,cap_net_raw+eip"

This is my log:

> 2020-10-17 11:23:13 ERROR (Thread-6) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/home/homeassistant/.homeassistant/custom_components/mitemp_bt/sensor.py", line 137, in run
    mysocket = aiobs.create_bt_socket(self._interface)
  File "/srv/homeassistant/lib/python3.9/site-packages/aioblescan/aioblescan.py", line 1280, in create_bt_socket
    sock = socket.socket(family=socket.AF_BLUETOOTH,
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'
2020-10-17 11:24:14 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/mitemp_bt/sensor.py", line 805, in update_ble
    discover_ble_devices(config, aeskeys, whitelist)
  File "/home/homeassistant/.homeassistant/custom_components/mitemp_bt/sensor.py", line 562, in discover_ble_devices
    jres = scanner.stop()
  File "/home/homeassistant/.homeassistant/custom_components/mitemp_bt/sensor.py", line 411, in stop
    if dumpthread.isAlive():
AttributeError: 'HCIdump' object has no attribute 'isAlive'
<

It's on Home Assistant Core on Python env on Raspberry Pi4.

I understand that the script can't access the HCI interface, but I dont know why. I change the permission of custom component folder to 777 but nothing.
Anyone can help me?

**Comment by Ernst79** [comment]
I googled the first error (AttributeError: module 'socket' has no attribute) and it seems that your python installation doesn’t have Bluetooth. 

See this [issue](https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/issues/19)

`Your python binary was built without Bluetooth support. You can install python from another repository that supports Bluetooth or compile it yourself. Make sure you have all the bluetooth libraries installed on your distro before compiling it. `

**Comment by tirkarthi** [comment]
`threading.Thread.isAlive` has been deprecated and removed in favour of `is_alive` . `is_alive` is present in both Python 2 and 3. I have raised #124 to fix this.

**Comment by Ernst79** [comment]
Thanks, I will test this on Python 3.8 today and will make a new release.

**Comment by giuscond** [comment]
Thank you for your help.

If it can be usefull, I forgot to say that I'm on Python 3.9

**Comment by Ernst79** [comment]
0.7.3 is released.
