### ISSUE TITLE
Error doing job: Future exception was never retrieved HassOS 64bit 4.15 mitemp_bt 0.7.5 work only couple minutes after start

### ISSUE THREAD

**Issue by shirou93** [custom-components/sensor.mitemp_bt#131]
Hardware: RPI4 4GB

I try downgrade to HassOS 4.13 still no work.

I have 2x LYWSD03MMC and today stopped working

My LYWSD02 show battery level attribute and no showing temp/humidity. Sometimes when restart show corretly and freeze.

`Logger: homeassistant
Source: custom_components/mitemp_bt/sensor.py:696
First occurred: 1:12:02 (1 occurrences)
Last logged: 1:12:02

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mitemp_bt/sensor.py", line 804, in update_ble
    discover_ble_devices(config, aeskeys, whitelist)
  File "/config/custom_components/mitemp_bt/sensor.py", line 696, in discover_ble_devices
    setattr(sensors[b_i], "_state", batt[mac])
IndexError: list index out of range
`

**Comment by Ernst79** [comment]
@Magalex2x14 Do you have an idea? LYWSD02 doesn't have battery info, so I think something goes wrong due to the `batt_entities: true`, which does work for the LYWSD03MMC sensors, but doesn't for LYWSD02?

I think if we have to change line 695 in sensor.py from 

`if config[CONF_BATT_ENTITIES]:`

to 

`if config[CONF_BATT_ENTITIES] and (b_i != 9):`

but I don't have these sensors. It should also have been filtered by line 694 already?

**Comment by shirou93** [comment]
> @Magalex2x14 Do you have an idea? LYWSD02 doesn't have battery info, so I think something goes wrong due to the `batt_entities: true`, which does work for the LYWSD03MMC sensors, but doesn't for LYWSD02?
> 
> I think if we have to change line 695 in sensor.py from
> 
> `if config[CONF_BATT_ENTITIES]:`
> 
> to
> 
> `if config[CONF_BATT_ENTITIES] and (b_i != 9):`
> 
> but I don't have these sensors. It should also have been filtered by line 694 already?

![image](https://user-images.githubusercontent.com/59237288/97327984-d349c700-1875-11eb-85a4-dd5c6976e49c.png)

When i change batt_entities to false is got working.

**Comment by Magalex2x14** [comment]
Look at line 672. This condition is checked before creating the battery sensor entity... In addition, line 695 is not executed if the sensor mac-address is not in the batt dictionary (which is filled in line 627, that is, when the data contains information about the battery) ... It turns out, the problem is that the parser finds battery data for this sensor, but we do not wait for it, and we do not create an entity for it... We need to fix 9 in const.py by 2 for this sensor. But before publishing this change, we need to figure it out ... Maybe a new firmware or a sensor revision?

**Comment by shirou93** [comment]
![image](https://user-images.githubusercontent.com/59237288/97329423-4ef84380-1877-11eb-927f-fcd7e98a9f57.png)
When i change battery in LYWSD02 i have 100% battery lvl i atrribute. Maybe update firmwae got battery level feature?

**Comment by Ernst79** [comment]
I was thinking exactly the same. is there a way to check the firmware

**Comment by Magalex2x14** [comment]
@shirou93 try this change in const.py:
![image](https://user-images.githubusercontent.com/4982025/97329690-5ffd8080-1888-11eb-930c-aea7f565bb84.png)

**Comment by shirou93** [comment]
> I was thinking exactly the same. is there a way to check the firmware

current firmware 1.1.2_00085

**Comment by Ernst79** [comment]
ESPhome is also reporting battery level available for LYWSD02 

https://github.com/esphome/issues/issues/1508

**Comment by Magalex2x14** [comment]
Perhaps we should only create an entity for the battery if the received data contains the appropriate information. The idea was that the necessary entities were created immediately (as quickly as possible) upon receiving ANY data from the sensor... So that they have the status "unknown" instead of "unavailable" in HA.

**Comment by shirou93** [comment]
> @shirou93 try this change in const.py:
> ![image](https://user-images.githubusercontent.com/4982025/97329690-5ffd8080-1888-11eb-930c-aea7f565bb84.png)

workig. I have battery entity in LYWSD02

**Comment by Magalex2x14** [comment]
Or just publish LYWSD02 with 2 instead of 9 for battery marked in the README for the availability of battery information in the new firmware.

**Comment by Ernst79** [comment]
Yes, that is an option. But changing it to 2 as above is also fine, I guess. If one doesn't have the latest firmware, it will show unknown, if one does it will report.

**Comment by Magalex2x14** [comment]
:)

**Comment by Ernst79** [comment]
Shall I make an update later this evening, or do you want to do it?

**Comment by Magalex2x14** [comment]
I'm a little busy, so do it as you can...

**Comment by shirou93** [comment]
Not showing humidity 
![image](https://user-images.githubusercontent.com/59237288/97332552-de532600-187a-11eb-8760-7d2ed6dfc381.png)

**Comment by Ernst79** [comment]
That is also reported at ESPhome, but others say that it should work. We have to dig a bit further

https://github.com/esphome/issues/issues/1508

**Comment by Magalex2x14** [comment]
I did not pay attention to this... Author of this post writes about the strange temperature. I think it is worth taking a closer look at the data received from such a sensor. @shirou93 is the temperature reading okay?

**Comment by Ernst79** [comment]
In the second post they say "Just use xiaomi_cgg1 after firmware x.x.x.0085" Not sure what they mean by that?

**Comment by shirou93** [comment]
> I did not pay attention to this... Author of this post writes about the strange temperature. I think it is worth taking a closer look at the data received from such a sensor. @shirou93 is the temperature reading okay?

temperature read is ok. Only no humidity

**Comment by Ernst79** [comment]
@shirou93 They mention errors above 30 degrees, so hold it in a hot space to check. They reported temperatures above 3000 degrees, which should be filtered out automatically (everything above 60 deg C is neglected). Could you set the log_spikes to true and check your logs? It should add a log entry about these filtered spikes.

**Comment by Magalex2x14** [comment]
> In the second post they say "Just use xiaomi_cgg1 after firmware x.x.x.0085" Not sure what they mean by that?

I do not understand too.
Our parser doesn't care what type of data it received (0D or 06), so humidity readings must be present anyway.

@shirou93 here's what we can try also:
1. remove the whole [line of code with LYWSD02](https://github.com/custom-components/sensor.mitemp_bt/issues/131#issuecomment-717353842) from const.py (or comment it out)
2. enable the report_unknown option as specified [here](https://github.com/custom-components/sensor.mitemp_bt/issues/131#issuecomment-717353842)
3.Restart HA and wait five minutes
4. The HA log will be filled with raw messages from the sensor - put them here, I'll see a little later.
5. roll back changes from point 1 and 2

Perhaps the raw data will give us an understanding of what is happening.

**Comment by Magalex2x14** [comment]
@shirou93 sorry, I was in a hurry... Instead of point 1, just replace the contents of const.py with this:

```python
"""Constants for the Xiaomi passive BLE monitor sensor integration."""
from homeassistant.const import (
    DEVICE_CLASS_POWER,
)

# Configuration options
CONF_ROUNDING = "rounding"
CONF_DECIMALS = "decimals"
CONF_PERIOD = "period"
CONF_LOG_SPIKES = "log_spikes"
CONF_USE_MEDIAN = "use_median"
CONF_ACTIVE_SCAN = "active_scan"
CONF_HCI_INTERFACE = "hci_interface"
CONF_BATT_ENTITIES = "batt_entities"
CONF_ENCRYPTORS = "encryptors"
CONF_REPORT_UNKNOWN = "report_unknown"
CONF_WHITELIST = "whitelist"
CONF_SENSOR_NAMES = "sensor_names"

# Default values for configuration options
DEFAULT_ROUNDING = True
DEFAULT_DECIMALS = 1
DEFAULT_PERIOD = 60
DEFAULT_LOG_SPIKES = False
DEFAULT_USE_MEDIAN = False
DEFAULT_ACTIVE_SCAN = False
DEFAULT_HCI_INTERFACE = 0
DEFAULT_BATT_ENTITIES = False
DEFAULT_REPORT_UNKNOWN = False
DEFAULT_WHITELIST = False


"""Fixed constants."""

# Sensor measurement limits to exclude erroneous spikes from the results
CONF_TMIN = -40.0
CONF_TMAX = 60.0
CONF_HMIN = 0.0
CONF_HMAX = 99.9

# Xiaomi sensor types dictionary for adv parser
XIAOMI_TYPE_DICT = {
    b'\x98\x00': "HHCCJCY01",
    b'\xAA\x01': "LYWSDCGQ",
##    b'\x5B\x04': "LYWSD02",
    b'\x47\x03': "CGG1",
    b'\x5D\x01': "HHCCPOT002",
    b'\xBC\x03': "GCLS002",
    b'\x5B\x05': "LYWSD03MMC",
    b'\x76\x05': "CGD1",
    b'\xDF\x02': "JQJCY01YM",
    b'\x0A\x04': "WX08ZM",
    b'\x87\x03': "MHO-C401",
    b'\xd3\x06': "MHO-C303"
}


# Sensor type indexes dictionary
# Temperature, Humidity, Moisture, Conductivity, Illuminance, Formaldehyde, Consumable, Switch, Battery
# Measurement type T  H  M  C  I  F  Cn Sw B   9 - no measurement
MMTS_DICT = {
    'HHCCJCY01' : [0, 9, 1, 2, 3, 9, 9, 9, 9],
    'GCLS002'   : [0, 9, 1, 2, 3, 9, 9, 9, 9],
    'HHCCPOT002': [9, 9, 0, 1, 9, 9, 9, 9, 9],
    'LYWSDCGQ'  : [0, 1, 9, 9, 9, 9, 9, 9, 2],
 ##   'LYWSD02'   : [0, 1, 9, 9, 9, 9, 9, 9, 9],
    'CGG1'      : [0, 1, 9, 9, 9, 9, 9, 9, 2],
    'LYWSD03MMC': [0, 1, 9, 9, 9, 9, 9, 9, 2],
    'CGD1'      : [0, 1, 9, 9, 9, 9, 9, 9, 2],
    'JQJCY01YM' : [0, 1, 9, 9, 9, 2, 9, 9, 3],
    'WX08ZM'    : [9, 9, 9, 9, 9, 9, 0, 1, 2],
    'MHO-C401'  : [0, 1, 9, 9, 9, 9, 9, 9, 2],
    'MHO-C303'  : [0, 1, 9, 9, 9, 9, 9, 9, 2]
}

# Switch binary sensor classes dict
SW_CLASS_DICT = {
    'WX08ZM'    : DEVICE_CLASS_POWER
}

# Consumable sensor name dict
CN_NAME_DICT = {
    'WX08ZM'    : "tablet_"
}

```

**Comment by shirou93** [comment]
> @shirou93 sorry, I was in a hurry... Instead of point 1, just replace the contents of const.py with this:
> 
> ```python
> """Constants for the Xiaomi passive BLE monitor sensor integration."""
> from homeassistant.const import (
>     DEVICE_CLASS_POWER,
> )
> 
> # Configuration options
> CONF_ROUNDING = "rounding"
> CONF_DECIMALS = "decimals"
> CONF_PERIOD = "period"
> CONF_LOG_SPIKES = "log_spikes"
> CONF_USE_MEDIAN = "use_median"
> CONF_ACTIVE_SCAN = "active_scan"
> CONF_HCI_INTERFACE = "hci_interface"
> CONF_BATT_ENTITIES = "batt_entities"
> CONF_ENCRYPTORS = "encryptors"
> CONF_REPORT_UNKNOWN = "report_unknown"
> CONF_WHITELIST = "whitelist"
> CONF_SENSOR_NAMES = "sensor_names"
> 
> # Default values for configuration options
> DEFAULT_ROUNDING = True
> DEFAULT_DECIMALS = 1
> DEFAULT_PERIOD = 60
> DEFAULT_LOG_SPIKES = False
> DEFAULT_USE_MEDIAN = False
> DEFAULT_ACTIVE_SCAN = False
> DEFAULT_HCI_INTERFACE = 0
> DEFAULT_BATT_ENTITIES = False
> DEFAULT_REPORT_UNKNOWN = False
> DEFAULT_WHITELIST = False
> 
> 
> """Fixed constants."""
> 
> # Sensor measurement limits to exclude erroneous spikes from the results
> CONF_TMIN = -40.0
> CONF_TMAX = 60.0
> CONF_HMIN = 0.0
> CONF_HMAX = 99.9
> 
> # Xiaomi sensor types dictionary for adv parser
> XIAOMI_TYPE_DICT = {
>     b'\x98\x00': "HHCCJCY01",
>     b'\xAA\x01': "LYWSDCGQ",
> ##    b'\x5B\x04': "LYWSD02",
>     b'\x47\x03': "CGG1",
>     b'\x5D\x01': "HHCCPOT002",
>     b'\xBC\x03': "GCLS002",
>     b'\x5B\x05': "LYWSD03MMC",
>     b'\x76\x05': "CGD1",
>     b'\xDF\x02': "JQJCY01YM",
>     b'\x0A\x04': "WX08ZM",
>     b'\x87\x03': "MHO-C401",
>     b'\xd3\x06': "MHO-C303"
> }
> 
> 
> # Sensor type indexes dictionary
> # Temperature, Humidity, Moisture, Conductivity, Illuminance, Formaldehyde, Consumable, Switch, Battery
> # Measurement type T  H  M  C  I  F  Cn Sw B   9 - no measurement
> MMTS_DICT = {
>     'HHCCJCY01' : [0, 9, 1, 2, 3, 9, 9, 9, 9],
>     'GCLS002'   : [0, 9, 1, 2, 3, 9, 9, 9, 9],
>     'HHCCPOT002': [9, 9, 0, 1, 9, 9, 9, 9, 9],
>     'LYWSDCGQ'  : [0, 1, 9, 9, 9, 9, 9, 9, 2],
>  ##   'LYWSD02'   : [0, 1, 9, 9, 9, 9, 9, 9, 9],
>     'CGG1'      : [0, 1, 9, 9, 9, 9, 9, 9, 2],
>     'LYWSD03MMC': [0, 1, 9, 9, 9, 9, 9, 9, 2],
>     'CGD1'      : [0, 1, 9, 9, 9, 9, 9, 9, 2],
>     'JQJCY01YM' : [0, 1, 9, 9, 9, 2, 9, 9, 3],
>     'WX08ZM'    : [9, 9, 9, 9, 9, 9, 0, 1, 2],
>     'MHO-C401'  : [0, 1, 9, 9, 9, 9, 9, 9, 2],
>     'MHO-C303'  : [0, 1, 9, 9, 9, 9, 9, 9, 2]
> }
> 
> # Switch binary sensor classes dict
> SW_CLASS_DICT = {
>     'WX08ZM'    : DEVICE_CLASS_POWER
> }
> 
> # Consumable sensor name dict
> CN_NAME_DICT = {
>     'WX08ZM'    : "tablet_"
> }
> ```

no problem :) You forgot add loger in config. I check in documentation :)

2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -52, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04eb5d8861002ee7090a10016400cc
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -48, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04ec5d8861002ee7090610029402d0
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -61, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04ed5d8861002ee709041002e500c3
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -48, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04ee5d8861002ee7090a10016400d0
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -61, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04ef5d8861002ee7090610029402c3
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -49, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04f05d8861002ee709041002e500cf
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -60, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04f15d8861002ee7090a10016400c4
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -52, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04f25d8861002ee7090610029402cc
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -52, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04f45d8861002ee7090a10016400cc
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -61, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04f55d8861002ee7090610029402c3
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -48, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04f65d8861002ee709041002e500d0
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -52, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04f65d8861002ee709041002e500cc
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -61, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04f75d8861002ee7090a10016400c3
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -49, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04f85d8861002ee7090610029402cf
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -61, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04f95d8861002ee709041002e500c3
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -48, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04fa5d8861002ee7090a10016400d0
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -61, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04fb5d8861002ee7090610029402c3
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -49, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04fc5d8861002ee709041002e500cf
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -61, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04fd5d8861002ee7090a10016400c3
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -49, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04fe5d8861002ee7090610029402cf
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -61, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04ff5d8861002ee709041002e500c3
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -49, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04005d8861002ee7090a10016400cf
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -61, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04015d8861002ee7090610029402c3
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -52, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04035d8861002ee7090a10016400cc
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -60, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04045d8861002ee7090610029402c4
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -52, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04055d8861002ee709041002e500cc
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -52, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04075d8861002ee7090610029402cc
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -60, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04085d8861002ee709041002e500c4
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -48, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04095d8861002ee7090a10016400d0
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -60, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b040a5d8861002ee7090610029402c4
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -48, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b040c5d8861002ee7090a10016400d0
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -48, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b040e5d8861002ee709041002e500d0
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -52, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b040f5d8861002ee7090a10016400cc
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -49, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04105d8861002ee7090610029402cf
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -61, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04115d8861002ee709041002e500c3
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -49, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04125d8861002ee7090a10016400cf
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -52, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04145d8861002ee709041002e600cc
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -60, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04155d8861002ee7090a10016400c4
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -48, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04165d8861002ee7090610029402d0
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -44, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04175d8861002ee709041002e600d4
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -49, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04185d8861002ee7090a10016400cf
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -60, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04195d8861002ee7090610029402c4
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -48, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b041a5d8861002ee709041002e500d0
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -60, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b041b5d8861002ee7090a10016400c4
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -49, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b041c5d8861002ee7090610029402cf
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -61, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b041d5d8861002ee709041002e500c3
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -49, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b041e5d8861002ee7090a10016400cf
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -61, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b041f5d8861002ee7090610029402c3
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -48, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04205d8861002ee709041002e500d0
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -61, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04215d8861002ee7090a10016400c3
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -52, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04235d8861002ee709041002e500cc
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -60, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04245d8861002ee7090a10016400c4
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -49, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04255d8861002ee7090610029402cf
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -52, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04255d8861002ee7090610029402cc
2020-10-27 18:37:37 INFO (SyncWorker_27) [custom_components.mitemp_bt.sensor] BLE ADV from UNKNOWN: RSSI: -52, MAC: E72E0061885D, ADV: 043e28020100005d8861002ee71c02010603021a18141695fe70205b04275d8861002ee7090a10016400cc

**Comment by shirou93** [comment]
> @shirou93 They mention errors above 30 degrees, so hold it in a hot space to check. They reported temperatures above 3000 degrees, which should be filtered out automatically (everything above 60 deg C is neglected). Could you set the log_spikes to true and check your logs? It should add a log entry about these filtered spikes.

![image](https://user-images.githubusercontent.com/59237288/97341336-3a22ac80-1885-11eb-98c7-5648792bf476.png)

correct.

**Comment by Magalex2x14** [comment]
Yes, I see humidity in the raw data. Perhaps it was a page refresh issue?
So everything looks good?

**Comment by shirou93** [comment]
@Magalex2x14  everything good. Only one change:
![image](https://user-images.githubusercontent.com/59237288/97344123-a2bf5880-1888-11eb-8928-1008912cf832.png)

Thanks

**Comment by Ernst79** [comment]
Thanks. I will make a new release tonight after updating the readme.
