### ISSUE TITLE
Update to 0.4.0 causes Home Assistant crashes

### ISSUE THREAD

**Issue by ma-zal** [custom-components/sensor.mitemp_bt#16]
I am reporting the issue during upgrade from 0.4.0-beta5 to 0.4.0 final.
When I pressed "UPDATE" button in HACS, Home Assistant stop to working.

```
homeassistant    | 2019-12-22 23:03:52 INFO (MainThread) [hacs] Running set_state for custom-components/sensor.mitemp_bt
homeassistant    | 2019-12-22 23:03:52 INFO (MainThread) [hacs] Running update for custom-components/sensor.mitemp_bt
homeassistant    | 2019-12-22 23:03:56 INFO (MainThread) [hacs] Running set_state for custom-components/sensor.mitemp_bt
homeassistant    | 2019-12-22 23:03:56 INFO (MainThread) [hacs] Running install for custom-components/sensor.mitemp_bt
homeassistant    | 2019-12-22 23:03:59 INFO (MainThread) [homeassistant.components.websocket_api.http.connection.1915840048] Connection closed by client
homeassistant    | Exception in thread Thread-1:
homeassistant    | Traceback (most recent call last):
homeassistant    |   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
homeassistant    |     self.run()
homeassistant    |   File "/usr/local/lib/python3.7/threading.py", line 870, in run
homeassistant    |     self._target(*self._args, **self._kwargs)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/util/logging.py", line 85, in _process
homeassistant    |     self._queue.get(), self.loop
homeassistant    |   File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 433, in result
homeassistant    |     raise CancelledError()
homeassistant    | concurrent.futures._base.CancelledError
homeassistant    |
homeassistant    | Config directory: /config
homeassistant    | Traceback (most recent call last):
homeassistant    |   File "/usr/src/homeassistant/homeassistant/__main__.py", line 396, in <module>
homeassistant    |     sys.exit(main())
homeassistant    |   File "/usr/src/homeassistant/homeassistant/__main__.py", line 388, in main
homeassistant    |     exit_code = asyncio_run(setup_and_run_hass(config_dir, args))
homeassistant    |   File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
homeassistant    |     return loop.run_until_complete(main)
homeassistant    |   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 566, in run_until_complete
homeassistant    |     self.run_forever()
homeassistant    |   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 534, in run_forever
homeassistant    |     self._run_once()
homeassistant    |   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1771, in _run_once
homeassistant    |     handle._run()
homeassistant    |   File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
homeassistant    |     self._context.run(self._callback, *self._args)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 18, in _handle_async_response
homeassistant    |     await func(hass, connection, msg)
homeassistant    |   File "/config/custom_components/hacs/ws_api_handlers.py", line 192, in hacs_repository
homeassistant    |     await repository.install()
homeassistant    |   File "/config/custom_components/hacs/repositories/repository.py", line 382, in install
homeassistant    |     self.ref,
homeassistant    |   File "/config/custom_components/hacs/repositories/repository.py", line 484, in download_content
homeassistant    |     directory_path, self.ref
homeassistant    |   File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
homeassistant    |     ret = await target(*args, **kwargs)
homeassistant    |   File "/usr/local/lib/python3.7/site-packages/aiogithubapi/repository.py", line 92, in get_contents
homeassistant    |     raise AIOGitHubException(f"GitHub returned {response.status} for {url}")
homeassistant    | aiogithubapi.exceptions.AIOGitHubException: GitHub returned 404 for https://api.github.com/repos/custom-components/sensor.mitemp_bt/contents/custom_components/mitemp_bt
```

When I restart the HA, and click to HACS -> Installed -> Xiaomi BLE... so it goes to crash with similar message again. In logs the error is similar.
Note:  The directory `mitemp_bt` is missing in `custom_components` directory now.

```
homeassistant    | 2019-12-22 23:21:56 INFO (MainThread) [hacs] Running set_state for custom-components/sensor.mitemp_bt
homeassistant    | 2019-12-22 23:21:56 INFO (MainThread) [hacs] Running update for custom-components/sensor.mitemp_bt
homeassistant    | 2019-12-22 23:21:59 INFO (MainThread) [homeassistant.components.websocket_api.http.connection.1874031024] Connection closed by client
homeassistant    | Traceback (most recent call last):
homeassistant    |   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
... 
```

**Comment by ma-zal** [comment]
Looks like problem somewhere in HACS. When I upgraded to last 0.19, it stopped to crash whole Home Assistant. But 404 on GitHub is still pressent in logs :(

**Comment by ma-zal** [comment]
Manual install (Github files -> custom_components/mitemp_bt) works. So problem is somewhere in HACS integration installation process.

- I reactivated the HACS and generates new GitHub token - did not help.
- I upgraded HACS, did not help.
- I restarted whole server, did not help

**Comment by Magalex2x14** [comment]
Can you open this link via web-browser? https://api.github.com/repos/custom-components/sensor.mitemp_bt/contents/custom_components/mitemp_bt

**Comment by ma-zal** [comment]
Yes, the url is working from browser, and also by `wget` in server. It is really weird, why HACS is logging it as 404.
It looks like as some problem in my local HACS instance, not in the `sensor.mitemp_bt` library itself. So closing the ticket here.

**Comment by ma-zal** [comment]
Adding info, if somebody will have same problem. Try this steps, that helps me.

1) Stop Home Assistant server
2) Delete all files with name `hacs` in `.storage` directory.
3) Start server and wait until whole initialization is done (takes couple of minutes in Raspberry).
