### ISSUE TITLE
Error crashes supervisor

### ISSUE THREAD

**Issue by borpin** [custom-components/sensor.mitemp_bt#71]
```
  File "/usr/local/lib/python3.7/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
2020-04-29 02:38:09 ERROR (SyncWorker_10) [custom_components.mitemp_bt.sensor] Error during Bluetooth LE scan: Event loop is closed
2020-04-29 02:38:29 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 274, in recuring_tasks_installed
    await self.data.async_write()
  File "/config/custom_components/hacs/hacsbase/data.py", line 72, in async_write
    await async_save_to_store(self.hacs.hass, "repositories", content)
  File "/config/custom_components/hacs/store.py", line 19, in async_save_to_store
    await store.async_save(data)
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 136, in async_save
    await self._async_handle_write_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 197, in _async_handle_write_data
    self._write_data, self.path, data
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 208, in _write_data
    json_util.save_json(path, data, self._private, encoder=self._encoder)
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 70, in save_json
    fdesc.write(json_data)
  File "/usr/local/lib/python3.7/tempfile.py", line 481, in func_wrapper
    return func(*args, **kwargs)
MemoryError
2020-04-29 02:39:05 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal read error on socket transport
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 814, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
MemoryError


2020-04-29 09:08:40 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 274, in recuring_tasks_installed
    await self.data.async_write()
  File "/config/custom_components/hacs/hacsbase/data.py", line 72, in async_write
    await async_save_to_store(self.hacs.hass, "repositories", content)
  File "/config/custom_components/hacs/store.py", line 19, in async_save_to_store
    await store.async_save(data)
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 136, in async_save
    await self._async_handle_write_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 197, in _async_handle_write_data
    self._write_data, self.path, data
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 208, in _write_data
    json_util.save_json(path, data, self._private, encoder=self._encoder)
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 56, in save_json
    json_data = json.dumps(data, sort_keys=True, indent=4, cls=encoder)
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 202, in encode
    return ''.join(chunks)
MemoryError
2020-04-29 09:09:28 ERROR (SyncWorker_11) [custom_components.mitemp_bt.sensor] Error during Bluetooth LE scan: Event loop is closed
```

On a supervised HA install on Raspbian.

Not sure if this is cause by this module, but is all I have installed by HACS.

**Comment by Magalex2x14** [comment]
@borpin  do you monitor the use of RAM? It seems that new threads cannot be created due to lack of RAM.

**Comment by Magalex2x14** [comment]
@borpin Is there any result in solving your problem?
I close this issue, reopen it freely, if necessary.

**Comment by borpin** [comment]
No it seemed to sort itself out. Sorry should have closed it.
