### ISSUE TITLE
AssertionError when trying to connect to LYWSD03MMC

### ISSUE THREAD

**Issue by smartjinyu** [custom-components/sensor.mitemp_bt#86]
Hi,

I'm trying to connect to LYWSD03MMC but got AssertionError. My platform information as following:

> Device: Raspberry Pi 4B 4GB
OS: Ubuntu Server 20.04 LTS
Kernel: Linux ubuntu 5.4.0-1012-raspi #12-Ubuntu SMP Wed May 27 04:08:35 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
Docker: Docker version 19.03.11, build 42e35e6
HA: Home Assistant 0.112.0.dev20200621

I ran HA in the docker container, and download the latest custom mitemp_bt from this repo. `configuration.yaml` snippet as follows:

> sensor:
 \- platform: mitemp_bt
     encryptors:
            'A4:C1:38:88:56:XX': '7eb471177474a27dd67551b454d872xx'

I can successfully connect to the LYWSDCGQ model, but failed for LYWSD03MMC.

Logs:

> Home Assistant attempting to restart.
Restarting Home Assistant
2020-06-21 20:58:29 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for mitemp_bt which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-21 20:58:30 DEBUG (SyncWorker_0) [custom_components.mitemp_bt_custom.sensor] Starting
2020-06-21 20:58:30 DEBUG (SyncWorker_0) [custom_components.mitemp_bt_custom.sensor] Spawning HCIdump thread(s).
2020-06-21 20:58:30 DEBUG (SyncWorker_0) [custom_components.mitemp_bt_custom.sensor] HCIdump thread: Init
2020-06-21 20:58:30 DEBUG (SyncWorker_0) [custom_components.mitemp_bt_custom.sensor] HCIdump thread: Init finished
2020-06-21 20:58:30 DEBUG (SyncWorker_0) [custom_components.mitemp_bt_custom.sensor] Starting HCIdump thread for hci0
2020-06-21 20:58:30 DEBUG (Thread-2) [custom_components.mitemp_bt_custom.sensor] HCIdump thread: Run
2020-06-21 20:58:30 DEBUG (SyncWorker_0) [custom_components.mitemp_bt_custom.sensor] HCIdump threads count = 1
2020-06-21 20:58:30 DEBUG (SyncWorker_0) [custom_components.mitemp_bt_custom.sensor] 1 encryptors mac:key pairs loaded.
2020-06-21 20:58:30 DEBUG (SyncWorker_0) [custom_components.mitemp_bt_custom.sensor] 0 whitelist item(s) loaded.
2020-06-21 20:58:30 DEBUG (Thread-2) [custom_components.mitemp_bt_custom.sensor] HCIdump thread: Connection
2020-06-21 20:58:30 DEBUG (Thread-2) [custom_components.mitemp_bt_custom.sensor] HCIdump thread: Connected
2020-06-21 20:58:30 DEBUG (Thread-2) [custom_components.mitemp_bt_custom.sensor] HCIdump thread: start main event_loop
2020-06-21 20:58:31 DEBUG (SyncWorker_0) [custom_components.mitemp_bt_custom.sensor] update_ble called
2020-06-21 20:58:31 DEBUG (SyncWorker_0) [custom_components.mitemp_bt_custom.sensor] First run, skip parsing.
2020-06-21 20:59:32 DEBUG (SyncWorker_19) [custom_components.mitemp_bt_custom.sensor] update_ble called
2020-06-21 20:59:32 DEBUG (SyncWorker_19) [custom_components.mitemp_bt_custom.sensor] Discovering Bluetooth LE devices
2020-06-21 20:59:32 DEBUG (SyncWorker_19) [custom_components.mitemp_bt_custom.sensor] Time to analyze...
2020-06-21 20:59:32 DEBUG (SyncWorker_19) [custom_components.mitemp_bt_custom.sensor] Getting data from HCIdump thread
2020-06-21 20:59:32 DEBUG (SyncWorker_19) [custom_components.mitemp_bt_custom.sensor] HCIdump thread: joining
2020-06-21 20:59:32 DEBUG (Thread-2) [custom_components.mitemp_bt_custom.sensor] HCIdump thread: main event_loop stopped, finishing
2020-06-21 20:59:32 DEBUG (Thread-2) [custom_components.mitemp_bt_custom.sensor] HCIdump thread: Run finished
2020-06-21 20:59:32 DEBUG (SyncWorker_19) [custom_components.mitemp_bt_custom.sensor] HCIdump thread: joined
2020-06-21 20:59:32 DEBUG (SyncWorker_19) [custom_components.mitemp_bt_custom.sensor] Spawning HCIdump thread(s).
2020-06-21 20:59:32 DEBUG (SyncWorker_19) [custom_components.mitemp_bt_custom.sensor] HCIdump thread: Init
2020-06-21 20:59:32 DEBUG (SyncWorker_19) [custom_components.mitemp_bt_custom.sensor] HCIdump thread: Init finished
2020-06-21 20:59:32 DEBUG (SyncWorker_19) [custom_components.mitemp_bt_custom.sensor] Starting HCIdump thread for hci0
2020-06-21 20:59:32 DEBUG (Thread-35) [custom_components.mitemp_bt_custom.sensor] HCIdump thread: Run
2020-06-21 20:59:32 DEBUG (SyncWorker_19) [custom_components.mitemp_bt_custom.sensor] HCIdump threads count = 1
2020-06-21 20:59:32 DEBUG (Thread-35) [custom_components.mitemp_bt_custom.sensor] HCIdump thread: Connection
2020-06-21 20:59:32 DEBUG (Thread-35) [custom_components.mitemp_bt_custom.sensor] HCIdump thread: Connected
2020-06-21 20:59:32 DEBUG (Thread-35) [custom_components.mitemp_bt_custom.sensor] HCIdump thread: start main event_loop
2020-06-21 20:59:32 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mitemp_bt_custom/sensor.py", line 775, in update_ble
    discover_ble_devices(config, aeskeys, whitelist)
  File "/config/custom_components/mitemp_bt_custom/sensor.py", line 683, in discover_ble_devices
    sensors[t_i], mac, config, temp_m_data[mac]
  File "/config/custom_components/mitemp_bt_custom/sensor.py", line 499, in calc_update_state
    entity_to_update.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 426, in schedule_update_ha_state
    assert self.hass is not None
AssertionError

I can connect to this LYWSD03MMC model when using Raspbian OS (also run HA in docker), but not able to do so after changing OS to Ubuntu. Also tried to delete & repair it in Mi Home app to get a new encryption key, but not helps either. I would appreciate if you have some hints on how to solve this. Thanks!

**Comment by antoweb** [comment]
Same problem with 0.112 stable, due this issue is opened 10 days ago I prefer to rollback to 0.111.4

**Comment by Ernst79** [comment]
Could you please try beta 0.7.1 and/or the new version 0.6.9 to see if it fixes your issue?

**Comment by antoweb** [comment]
> Could you please try beta 0.7.1 and/or the new version 0.6.9 to see if it fixes your issue?

With 0.71beta the sensor works good

**Comment by smartjinyu** [comment]
> Could you please try beta 0.7.1 and/or the new version 0.6.9 to see if it fixes your issue?

0.6.9 works for me. Thank you!
