### ISSUE TITLE
Exception in 112.3 - URGENT

### ISSUE THREAD

**Issue by borpin** [custom-components/sensor.mitemp_bt#93]
Exception seen on first starting 112.3

```
2020-07-07 06:56:29 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mitemp_bt/sensor.py", line 775, in update_ble
    discover_ble_devices(config, aeskeys, whitelist)
  File "/config/custom_components/mitemp_bt/sensor.py", line 683, in discover_ble_devices
    sensors[t_i], mac, config, temp_m_data[mac]
  File "/config/custom_components/mitemp_bt/sensor.py", line 499, in calc_update_state
    entity_to_update.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 416, in schedule_update_ha_state
    assert self.hass is not None
AssertionError
```

**Comment by borpin** [comment]
I have dropped this code in around the culprit

```
            try:
                entity_to_update.schedule_update_ha_state()
            except:
                _LOGGER.debug("BPO -- Sensor %s not yet ready for update", sensor_mac)
                success = False
            success = True
```

I'm seeing this in the log

```
2020-07-07 07:28:48 DEBUG (SyncWorker_10) [custom_components.mitemp_bt.sensor] BPO -- Sensor 4C65A8D8E0D8 not yet ready for update
2020-07-07 07:28:48 DEBUG (SyncWorker_10) [custom_components.mitemp_bt.sensor] BPO -- Sensor 4C65A8D8E0D8 not yet ready for update
2020-07-07 07:28:48 DEBUG (SyncWorker_10) [custom_components.mitemp_bt.sensor] BPO -- Sensor 4C65A8D8E00C not yet ready for update
2020-07-07 07:28:48 DEBUG (SyncWorker_10) [custom_components.mitemp_bt.sensor] BPO -- Sensor 4C65A8D8E00C not yet ready for update
2020-07-07 07:28:48 DEBUG (SyncWorker_10) [custom_components.mitemp_bt.sensor] BPO -- Sensor 4C65A8DC8A9B not yet ready for update
2020-07-07 07:28:48 DEBUG (SyncWorker_10) [custom_components.mitemp_bt.sensor] BPO -- Sensor 4C65A8DC8A9B not yet ready for update
2020-07-07 07:28:48 DEBUG (SyncWorker_10) [custom_components.mitemp_bt.sensor] BPO -- Sensor 4C65A8D9591A not yet ready for update
2020-07-07 07:28:48 DEBUG (SyncWorker_10) [custom_components.mitemp_bt.sensor] BPO -- Sensor 4C65A8D9591A not yet ready for update
2020-07-07 07:28:48 DEBUG (SyncWorker_10) [custom_components.mitemp_bt.sensor] Finished. Parsed: 1563 hci events, 5 xiaomi devices.
```

Note I just copied a log message so I got something on the exception 😀.

HTH

**Comment by camfrout** [comment]
Same error on my side but on 0.112.2. 
And the quick fix makes it work again as well.

**Comment by borpin** [comment]
Apparently there is a fix in the system somewhere.  Glad I could help.
